// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuhitcjimtdjffdumptw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1aGl0Y2ppbXRkamZmZHVtcHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Mjg5MTIsImV4cCI6MjA3MTUwNDkxMn0.prg9z8ao84L9Z3xs7LYmGnqD-cCMmeL1KfcfoUAxSW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});